http:
  address: ${GUI_ADDR}

dns:
  bind_hosts:
${BIND_BLOCK}

  upstream_dns:
    - ${KRESD3_IP}:${DNS_PORT}

  bootstrap_dns:
    - ${ipv4a}
    - ${ipv4b}
    - ${ipv6a}
    - ${ipv6b}
  fallback_dns:
    - ${ipv4a}
    - ${ipv4b}
    - ${ipv6a}
    - ${ipv6b}

  allowed_clients:
    - ${SVPN_NET4}
    - ${FVPN_NET4}
${ALLOW_BLOCK}