[Definition]

# ---------- init ----------
actionstart = ipset create ipset-block  hash:ip          timeout 0 comment maxelem 200000 -exist && \
              ipset create ipset-block6 hash:ip family inet6 timeout 0 comment maxelem 200000 -exist && \
              (iptables  -C <chain> -m set --match-set ipset-block  src -j DROP || \
               iptables  -I <chain> 1 -m set --match-set ipset-block  src -j DROP) && \
              (ip6tables -C <chain> -m set --match-set ipset-block6 src -j DROP || \
               ip6tables -I <chain> 1 -m set --match-set ipset-block6 src -j DROP)

# ---------- ban / unban ----------
actionban   = ipset add ipset-block  <ip> timeout <bantime> comment "f2b-<name> $(date '+%%F %%T')" -exist && \
              ipset add ipset-block6 <ip> timeout <bantime> comment "f2b-<name> $(date '+%%F %%T')" -exist || true

actionunban = ipset del ipset-block  <ip> -exist && \
              ipset del ipset-block6 <ip> -exist || true

# ---------- defaults ----------
[Init]
chain = INPUT